$path = 'f:\repos\CSharp\PiDesktop_054\pi-network-desktop\resources\app.asar-repack\PiNodeMonitorWinForm\Form1.cs'
$lines = Get-Content $path
$start = -1
$end = -1

# Find the start and end of the Wallet/Footer init block
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '// Wallet UI Implementation') {
        $start = $i
    }
    if ($lines[$i] -match 'pnlFooter\.Resize \+=') {
        $end = $i + 4 # Capture a bit more of the footer logic
        break
    }
}

if ($start -ge 0 -and $end -ge 0) {
    $newLines = @(
        '            // ---------------------------------------------------------',
        '            // Wallet & Footer UI (FlowLayout Integration)',
        '            // ---------------------------------------------------------',
        '            ',
        '            // 1. Wallet Status Label',
        '            lblBalance = new Label();',
        '            lblBalance.Text = "Wallet: -- π";',
        '            lblBalance.Font = new Font("Segoe UI", 10, FontStyle.Bold);',
        '            lblBalance.ForeColor = Color.Gold;',
        '            lblBalance.BackColor = Color.Transparent;',
        '            lblBalance.AutoSize = true;',
        '            lblBalance.Margin = new Padding(0, 20, 0, 5);',
        '            mainFlow.Controls.Add(lblBalance);',
        '',
        '            // 2. Wallet Input Row (Horizontal Flow)',
        '            FlowLayoutPanel walletFlow = new FlowLayoutPanel();',
        '            walletFlow.FlowDirection = FlowDirection.LeftToRight;',
        '            walletFlow.AutoSize = true;',
        '            walletFlow.Margin = new Padding(0, 0, 0, 10);',
        '            walletFlow.WrapContents = false;',
        '',
        '            txtPublicKey = new TextBox();',
        '            txtPublicKey.PlaceholderText = "Paste Public Key (G...)";',
        '            txtPublicKey.Size = new Size(390, 25);',
        '            txtPublicKey.BackColor = Color.FromArgb(40, 40, 40);',
        '            txtPublicKey.ForeColor = Color.White;',
        '            txtPublicKey.BorderStyle = BorderStyle.FixedSingle;',
        '            walletFlow.Controls.Add(txtPublicKey);',
        '',
        '            btnSaveKey = new Button();',
        '            btnSaveKey.Text = "💾";',
        '            btnSaveKey.Size = new Size(35, 25);',
        '            btnSaveKey.FlatStyle = FlatStyle.Flat;',
        '            btnSaveKey.ForeColor = Color.White;',
        '            walletFlow.Controls.Add(btnSaveKey);',
        '',
        '            var btnSmsConfig = new Button();',
        '            btnSmsConfig.Text = "💬";',
        '            btnSmsConfig.Size = new Size(35, 25);',
        '            btnSmsConfig.FlatStyle = FlatStyle.Flat;',
        '            btnSmsConfig.ForeColor = Color.LightSkyBlue;',
        '            btnSmsConfig.Cursor = Cursors.Hand;',
        '            btnSmsConfig.Click += (s, e) => {',
        '                using (var frm = new SmsSettingsForm()) {',
        '                    if (frm.ShowDialog() == DialogResult.OK) {',
        '                        _smsService.LoadSettings();',
        '                        InitializeBot();',
        '                    }',
        '                }',
        '            };',
        '            walletFlow.Controls.Add(btnSmsConfig);',
        '',
        '            btnChangeWallet = new Button();',
        '            btnChangeWallet.Text = "Change Address";',
        '            btnChangeWallet.Size = new Size(120, 25);',
        '            btnChangeWallet.FlatStyle = FlatStyle.Flat;',
        '            btnChangeWallet.ForeColor = Color.Gray; ',
        '            btnChangeWallet.Cursor = Cursors.Hand;',
        '            walletFlow.Controls.Add(btnChangeWallet);',
        '',
        '            mainFlow.Controls.Add(walletFlow);',
        '',
        '            // 3. Multi-View & Mobile Connect Row (Horizontal Flow)',
        '            FlowLayoutPanel buttonFlow = new FlowLayoutPanel();',
        '            buttonFlow.FlowDirection = FlowDirection.LeftToRight;',
        '            buttonFlow.Size = new Size(470, 50);',
        '            buttonFlow.Margin = new Padding(0, 10, 0, 10);',
        '            buttonFlow.FlowDirection = FlowDirection.RightToLeft;',
        '',
        '            btnMobile = new Button();',
        '            btnMobile.Text = "📱 Mobile Connect";',
        '            btnMobile.Size = new Size(130, 40);',
        '            btnMobile.BackColor = Color.RebeccaPurple;',
        '            btnMobile.ForeColor = Color.White;',
        '            btnMobile.FlatStyle = FlatStyle.Flat;',
        '            btnMobile.Font = new Font("Segoe UI", 9, FontStyle.Bold);',
        '            btnMobile.Click += (s, e) => {',
        '                try {',
        '                    using (var qr = new QRForm($"http://{MobileServer.CurrentIpAddress}:{MobileServer.Port}")) {',
        '                        qr.ShowDialog(this);',
        '                    }',
        '                } catch (Exception ex) { MessageBox.Show(ex.Message); }',
        '            };',
        '            buttonFlow.Controls.Add(btnMobile);',
        '',
        '            Button btnMulti = new Button();',
        '            btnMulti.Text = "🖥️ Multi-View";',
        '            btnMulti.Size = new Size(130, 40);',
        '            btnMulti.BackColor = Color.Teal;',
        '            btnMulti.ForeColor = Color.White;',
        '            btnMulti.FlatStyle = FlatStyle.Flat;',
        '            btnMulti.Font = new Font("Segoe UI", 9, FontStyle.Bold);',
        '            btnMulti.Click += (s, e) => { new MultiMonitorForm().Show(); };',
        '            buttonFlow.Controls.Add(btnMulti);',
        '',
        '            mainFlow.Controls.Add(buttonFlow);',
        '',
        '            // Rest of Toggle Logic',
        '            Action<bool> ToggleWalletEdit = (editing) => {',
        '                txtPublicKey.Visible = editing;',
        '                btnSaveKey.Visible = editing;',
        '                btnChangeWallet.Visible = !editing;',
        '                if (editing) txtPublicKey.Focus();',
        '            };',
        '            btnChangeWallet.Click += (s, e) => ToggleWalletEdit(true);',
        '            btnSaveKey.Click += (s, e) => {',
        '                _walletService.SaveKey(txtPublicKey.Text);',
        '                MessageBox.Show("Wallet Key Saved!");',
        '                UpdateWalletBalanceAsync(); ',
        '                ToggleWalletEdit(false);',
        '            };',
        '            if (!string.IsNullOrEmpty(_walletService.PublicKey)) {',
        '                txtPublicKey.Text = _walletService.PublicKey;',
        '                ToggleWalletEdit(false); ',
        '            } else { ToggleWalletEdit(true); }',
        '',
        '            // 4. Dark Footer (External to Flow)',
        '            Panel pnlFooter = new Panel { Dock = DockStyle.Bottom, Height = 35, BackColor = Color.FromArgb(32, 32, 32) };',
        '            Label lblCopy = new Label { Text = "Copyright © 2025 GuruPia. All rights reserved.", ForeColor = Color.LightGray, Font = new Font("Segoe UI", 9), AutoSize = true, Location = new Point(10, 8) };',
        '            LinkLabel lnkDev = new LinkLabel { Text = "Developed by gurupia.github.io", LinkColor = Color.Gold, Font = new Font("Segoe UI", 9, FontStyle.Bold), AutoSize = true, Cursor = Cursors.Hand };',
        '            lnkDev.LinkClicked += (s, e) => { try { Process.Start(new ProcessStartInfo { FileName = "https://gurupia.github.io", UseShellExecute = true }); } catch {} };',
        '            pnlFooter.Controls.Add(lblCopy);',
        '            pnlFooter.Controls.Add(lnkDev);',
        '            this.Controls.Add(pnlFooter);',
        '            pnlFooter.Resize += (s, e) => { lnkDev.Location = new Point(pnlFooter.Width - lnkDev.Width - 15, 8); };',
        '            pnlFooter.BringToFront();'
    )
    
    $finalContent = $lines[0..($start - 1)] + $newLines + $lines[($end + 1)..($lines.Count - 1)]
    [System.IO.File]::WriteAllLines($path, $finalContent, [System.Text.Encoding]::UTF8)
    Write-Host "Successfully restored Wallet and Footer in Form1.cs"
}
else {
    Write-Error "Markers not found in Form1.cs: start=$start, end=$end"
}
