$path = 'f:\repos\CSharp\PiDesktop_054\pi-network-desktop\resources\app.asar-repack\PiNodeMonitorWinForm\Form1.Designer.cs'
$lines = Get-Content $path
$assemblyIndex = -1

for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '// Assembly') {
        $assemblyIndex = $i
        break
    }
}

if ($assemblyIndex -ge 0) {
    $newLines = @(
        '            // groupBoxControl - Node Control & Status',
        '            this.lblMainStatus.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);',
        '            this.lblMainStatus.ForeColor = System.Drawing.Color.Green;',
        '            this.lblMainStatus.Location = new System.Drawing.Point(10, 20);',
        '            this.lblMainStatus.Size = new System.Drawing.Size(200, 30);',
        '            this.lblMainStatus.Text = "Checking status...";',
        '            this.lblMainStatus.TextAlign = System.Drawing.ContentAlignment.TopCenter;',
        '',
        '            this.lblLocalBlockLabel.AutoSize = true;',
        '            this.lblLocalBlockLabel.Location = new System.Drawing.Point(10, 50);',
        '            this.lblLocalBlockLabel.Text = "Local block number:";',
        '',
        '            this.lblLocalBlockNum.AutoSize = true;',
        '            this.lblLocalBlockNum.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);',
        '            this.lblLocalBlockNum.Location = new System.Drawing.Point(140, 50);',
        '            this.lblLocalBlockNum.Text = "0";',
        '',
        '            this.lblRemoteBlockLabel.AutoSize = true;',
        '            this.lblRemoteBlockLabel.Location = new System.Drawing.Point(10, 70);',
        '            this.lblRemoteBlockLabel.Text = "Latest block number:";',
        '',
        '            this.lblRemoteBlockNum.AutoSize = true;',
        '            this.lblRemoteBlockNum.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);',
        '            this.lblRemoteBlockNum.Location = new System.Drawing.Point(140, 70);',
        '            this.lblRemoteBlockNum.Text = "0";',
        '',
        '            this.btnToggleNode.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);',
        '            this.btnToggleNode.Location = new System.Drawing.Point(10, 95);',
        '            this.btnToggleNode.Size = new System.Drawing.Size(200, 35);',
        '            this.btnToggleNode.Text = "Checking...";',
        '            this.btnToggleNode.UseVisualStyleBackColor = true;',
        '            this.btnToggleNode.Click += new System.EventHandler(this.btnToggleNode_Click);',
        '',
        '            // groupBox3 - Network Stats',
        '            this.label4.AutoSize = true;',
        '            this.label4.Location = new System.Drawing.Point(10, 30);',
        '            this.label4.Text = "Incoming:";',
        '            this.lblIncoming.AutoSize = true;',
        '            this.lblIncoming.Location = new System.Drawing.Point(100, 30);',
        '            this.lblIncoming.Text = "0";',
        '',
        '            this.label5.AutoSize = true;',
        '            this.label5.Location = new System.Drawing.Point(10, 55);',
        '            this.label5.Text = "Outgoing:";',
        '            this.lblOutgoing.AutoSize = true;',
        '            this.lblOutgoing.Location = new System.Drawing.Point(100, 55);',
        '            this.lblOutgoing.Text = "0";',
        '',
        '            this.label6.AutoSize = true;',
        '            this.label6.Location = new System.Drawing.Point(10, 80);',
        '            this.label6.Text = "Supporting:";',
        '            this.lblSupporting.AutoSize = true;',
        '            this.lblSupporting.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);',
        '            this.lblSupporting.Location = new System.Drawing.Point(100, 80);',
        '            this.lblSupporting.Text = "No";',
        '',
        '            // groupBox4 - Resources',
        '            this.label11.AutoSize = true;',
        '            this.label11.Location = new System.Drawing.Point(10, 25);',
        '            this.label11.Text = "Name:";',
        '            this.lblContainerStatus.AutoSize = true;',
        '            this.lblContainerStatus.Location = new System.Drawing.Point(70, 25);',
        '            this.lblContainerStatus.Text = "Checking...";',
        '',
        '            this.label8.AutoSize = true;',
        '            this.label8.Location = new System.Drawing.Point(10, 50);',
        '            this.label8.Text = "CPU:";',
        '            this.lblCPU.AutoSize = true;',
        '            this.lblCPU.Location = new System.Drawing.Point(70, 50);',
        '            this.lblCPU.Text = "...";',
        '',
        '            this.label10.AutoSize = true;',
        '            this.label10.Location = new System.Drawing.Point(10, 75);',
        '            this.label10.Text = "RAM:";',
        '            this.lblRAM.AutoSize = true;',
        '            this.lblRAM.Location = new System.Drawing.Point(70, 75);',
        '            this.lblRAM.Text = "...";',
        '',
        '            // groupBox5 - Ports',
        '            this.label12.AutoSize = true;',
        '            this.label12.Location = new System.Drawing.Point(20, 25);',
        '            this.label12.Text = "31401:";',
        '            this.lblPort01.AutoSize = true;',
        '            this.lblPort01.Location = new System.Drawing.Point(80, 25);',
        '            this.lblPort01.Text = "Checking";',
        '',
        '            this.label13.AutoSize = true;',
        '            this.label13.Location = new System.Drawing.Point(170, 25);',
        '            this.label13.Text = "31402:";',
        '            this.lblPort02.AutoSize = true;',
        '            this.lblPort02.Location = new System.Drawing.Point(230, 25);',
        '            this.lblPort02.Text = "Checking";',
        '',
        '            this.label14.AutoSize = true;',
        '            this.label14.Location = new System.Drawing.Point(320, 25);',
        '            this.label14.Text = "31403:";',
        '            this.lblPort03.AutoSize = true;',
        '            this.lblPort03.Location = new System.Drawing.Point(380, 25);',
        '            this.lblPort03.Text = "Checking";',
        '',
        '            // groupBox6 - Stats',
        '            this.lblUptime.AutoSize = true;',
        '            this.lblUptime.Location = new System.Drawing.Point(15, 25);',
        '            this.lblUptime.Text = "Uptime: 00:00:00";',
        '',
        '            this.lblAvailability.AutoSize = true;',
        '            this.lblAvailability.Location = new System.Drawing.Point(125, 25);',
        '            this.lblAvailability.Text = "Availability: 0.00%";',
        '',
        '            this.lblBonus.AutoSize = true;',
        '            this.lblBonus.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);',
        '            this.lblBonus.Location = new System.Drawing.Point(240, 25);',
        '            this.lblBonus.Text = "Bonus: 0.0000";',
        '',
        '            this.btnHelp.Location = new System.Drawing.Point(340, 20);',
        '            this.btnHelp.Size = new System.Drawing.Size(52, 26);',
        '            this.btnHelp.Text = "Help";',
        '            this.btnHelp.ForeColor = System.Drawing.Color.Black;',
        '            this.btnHelp.BackColor = System.Drawing.Color.FromArgb(224, 224, 224);',
        '            this.btnHelp.UseVisualStyleBackColor = false;',
        '            this.btnHelp.Click += new System.EventHandler(this.btnHelp_Click);',
        '',
        '            this.btnShowHistory.Location = new System.Drawing.Point(395, 20);',
        '            this.btnShowHistory.Size = new System.Drawing.Size(58, 26);',
        '            this.btnShowHistory.Text = "History";',
        '            this.btnShowHistory.ForeColor = System.Drawing.Color.Black;',
        '            this.btnShowHistory.BackColor = System.Drawing.Color.FromArgb(224, 224, 224);',
        '            this.btnShowHistory.UseVisualStyleBackColor = false;',
        '            this.btnShowHistory.Click += new System.EventHandler(this.btnShowHistory_Click);',
        ''
    )
    
    $finalContent = $lines[0..($assemblyIndex - 1)] + $newLines + $lines[$assemblyIndex..($lines.Count - 1)]
    [System.IO.File]::WriteAllLines($path, $finalContent, [System.Text.Encoding]::UTF8)
    Write-Host "Successfully restored all other groupBox labels"
}
else {
    Write-Error "Assembly marker not found"
}
